services:
  smtp:
    image: ghcr.io/missioninbox/postal:3.39.0
    command: postal smtp-server
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - /opt/postal/config:/config
    restart: unless-stopped

  worker:
    image: ghcr.io/missioninbox/postal:3.39.0
    command: postal worker
    network_mode: host
    volumes:
      - /opt/postal/config:/config
    restart: unless-stopped

  runner:
    profiles: ["tools"]
    image: ghcr.io/missioninbox/postal:3.39.0
    command: postal
    network_mode: host
    volumes:
      - /opt/postal/config:/config
